### ISSUE TITLE
[Feature] CICD 파이프라인 구축

### ISSUE THREAD

**Issue by JokerTrickster** [JokerTrickster/go_clean_architecture#24]
### 새로운 기능
- 요청자 : @JokerTrickster    
- What :  CICD 파이프라인 구축
- Why :  브랜치를 효율적으로 관리하기 위해서
- How :  아래 코멘트 작성

### Tasks
- [ ] dev 인프라 및 스크립트 작성
- [ ] stg 스크립트 작성
- [ ] prd 인프라 및 스크립트 작성

**Comment by JokerTrickster** [comment]
### 브랜치 종류 : 
 main / dev / stg / prd 

### 용도 : 
	- main : 최신 코드 유지 (dev, stg, prd 브랜치에 푸시를 할 경우 main에 항상 merge 되도록 )
	- dev : 모든 작업은 dev 브랜치에서 브랜치 따서 진행 (작업이 완료되면 main에 merge 함), 인프라 셋팅 필요
	- stg : prd 올리기 전 dev -> stg 코드 푸시, 인프라 셋팅 필요 없음
	- prd : 최신 코드는 운영 중인 코드, 인프라 필요

### semantic versioning rule
major : 하위호환되지 않은 변화가 추가될 때 
minor : 새 기능 추가나 내부 코드 개선 작업할 때 
patch : 버그 해결할 때 사용
